Foreground yes
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/ecos-clamd.sock
LocalSocketMode 600
FixStaleSocket no
TemporaryDirectory /tmp
OfficialDatabaseOnly yes
MaxFileSize 160M
MaxScanSize 512M
MaxRecursion 16
MaxFiles 50000
StreamMaxLength 160M
MaxScanTime 240000
AlertExceedsMax yes
MaxThreads 2
MaxQueue 4
MaxConnectionQueueLength 4
ReadTimeout 180
CommandReadTimeout 5
SendBufTimeout 120
IdleTimeout 300
SelfCheck 3600
